"""
Markdown / plain-text export for ClipStory.
"""

from datetime import datetime
from clipstory.db import store


def export_markdown(session_id: int, output_id: int | None = None) -> str:
    """
    Build a Markdown report string for the given session.

    Args:
        session_id: Session to export.
        output_id:  Specific output to embed. If None, uses the most recent one.

    Returns:
        Markdown string.
    """
    session = store.get_session(session_id)
    clips   = store.get_clips_for_session(session_id)
    outputs = store.get_outputs_for_session(session_id)

    # Select the output to embed
    output = None
    if output_id:
        output = next((o for o in outputs if o["id"] == output_id), None)
    elif outputs:
        output = outputs[0]  # most recent

    started  = datetime.fromisoformat(session["started_at"])
    ended    = datetime.fromisoformat(session["ended_at"]) if session.get("ended_at") else datetime.now()
    duration = int((ended - started).total_seconds() / 60)
    hours, mins = divmod(duration, 60)
    dur_str  = f"{hours}h {mins}m" if hours else f"{mins}m"

    lines = [
        f"# ClipStory — Session Report",
        f"",
        f"**Date:** {started.strftime('%B %d, %Y')}  ",
        f"**Started:** {started.strftime('%I:%M %p')}  ",
        f"**Duration:** {dur_str}  ",
        f"**Clips:** {len(clips)}  ",
        f"",
        "---",
        "",
    ]

    # LLM output section
    if output:
        from clipstory.llm.prompts import MODE_LABELS
        label = MODE_LABELS.get(output["mode"], output["mode"].title())
        lines += [
            f"## {label}",
            "",
            output["content"],
            "",
            "---",
            "",
        ]

    # Clip timeline
    lines += [
        "## Clip Timeline",
        "",
        "| # | Time | Type | Content |",
        "|---|------|------|---------|",
    ]
    for i, c in enumerate(clips, 1):
        ts      = c["copied_at"][:16].replace("T", " ")
        ctype   = c["content_type"].upper()
        content = c["content"].strip().replace("\n", " ")[:120]
        if c.get("page_title"):
            content = f"[{c['page_title']}]({content})"
        if c.get("is_redacted"):
            content += " ⚠️"
        lines.append(f"| {i} | {ts} | {ctype} | {content} |")

    lines += ["", "---", "", f"*Generated by ClipStory on {datetime.now().strftime('%Y-%m-%d %H:%M')}*"]

    return "\n".join(lines)


def filename_for_session(session_id: int, ext: str = "md") -> str:
    session = store.get_session(session_id)
    started = datetime.fromisoformat(session["started_at"])
    return f"clipstory_{started.strftime('%Y%m%d_%H%M')}_session{session_id}.{ext}"
